version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    command: ruby main.rb
    ports:
      - "4000:3000" # Si ton application utilise un serveur web

  tests:
    build:
      context: .
    volumes:
      - .:/app
    command: ruby run_tests.rb