@startuml

skinparam classAttributeIconSize 0

class Extractor {
  - http_client : HTTPClient
  - logger : Logger
  - newest_record_stored : JSON
  - oldest_record_retrieved : JSON
  - current_data : JSON
  - max_retries : Integer
  - endpoint : String
  + Extractor(max_retries: Integer)
  + extract(http_client : HTTPClient, endpoint: String, newest_record_stored: JSON) : JSON
  - handle_duplicate(current_data: JSON, oldest_record_stored: JSON) : void
  - handle_missing(current_data: JSON, oldest_record_stored: JSON) : void
  - get_missing_data(oldest_record_retrieved: JSON) : JSON
}

class HTTPClient {
  - base_url : String
  - headers : Hash
  - timeout : Integer
  + HTTPClient(base_url: String, headers: Hash, timeout: Integer)
  + get(endpoint: String, params: Hash) : JSON
  - make_request(uri: URI, request: Net::HTTP::Get) : Net::HTTPResponse
  - handle_response(response: Net::HTTPResponse) : JSON
}

class Logger {
  - log_path : String
  - last_log : String
  - file : File
  + Logger(log_path: String)
  + log_info(message: String) : void
  + log_error(error: String) : void
  + archive_log(archive_dir: String) : void
  - write_log(log_message: String) : void
  - timestamp() : String
}

Extractor ..> HTTPClient
Extractor ..> Logger

note as N1
  Title: Updated Class Diagram
  Date: 06.01.2025
  Authors: Benoît Pierrehumbert & Philippe Moeckli
end note

@enduml
