openapi: 3.0.3
info:
  title: Extract API Service
  version: 1.0.0
  description: API to extract data from a specified endpoint.
paths:
  /api/v1/data/extract:
    post:
      summary: Retrieve data
      description: Extracts data from the specified API endpoint.
      requestBody:
        description: The request body containing the target API endpoint.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                endpoint:
                  type: string
                  description: The target API endpoint from which to extract data.
      responses:
        '200':
          description: Data retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  dataSource:
                    type: string
                    description: The url to the extracted data.
                    example: https://s3.eu-south-1.amazonaws.com/dev.external.source.extract.cld.education/cache/6395b20f-42d6-4be4-b0cf-e5ff5fd73d10?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA2KFJKL4O5EQPXSVM%2F20250123%2Feu-south-1%2Fs3%2Faws4_request&X-Amz-Date=20250123T113557Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&X-Amz-Signature=4e9e7161bc3492fe74032b06b4a2eae31eb03c845a96702459304cc8d2dc97be
        '400':
          description: Bad request - Missing or invalid request body.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Missing endpoint parameter
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Max retries reached while trying to extract data
                  details:
                    type: string
                    example: Extraction process stopped after 3 retries